//go:build !ignore_autogenerated

/*
Copyright 2026 Flant JSC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageClass) DeepCopyInto(out *ObjectStorageClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ObjectStorageClass.
func (in *ObjectStorageClass) DeepCopy() *ObjectStorageClass {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ObjectStorageClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageClassList) DeepCopyInto(out *ObjectStorageClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ObjectStorageClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ObjectStorageClassList.
func (in *ObjectStorageClassList) DeepCopy() *ObjectStorageClassList {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ObjectStorageClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageClassSpec) DeepCopyInto(out *ObjectStorageClassSpec) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ObjectStorageClassSpec.
func (in *ObjectStorageClassSpec) DeepCopy() *ObjectStorageClassSpec {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageClassStatus) DeepCopyInto(out *ObjectStorageClassStatus) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ObjectStorageClassStatus.
func (in *ObjectStorageClassStatus) DeepCopy() *ObjectStorageClassStatus {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageClassStatus)
	in.DeepCopyInto(out)
	return out
}
